services:
  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:5002"
    environment:
      - RESET_DB=1

  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend

## no named volumes required